# -*- coding: utf-8 -*-
"""KMeansAppTF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j0f1JBkfb6ypG8eoMBvEsnUV9Yw2YtjT

Imports para el proyecto
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.cluster import SpectralClustering
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score, homogeneity_score, completeness_score, v_measure_score, adjusted_rand_score
import matplotlib.pyplot as plt
import seaborn as sns

"""Lectura de archivos CSV"""

# Leer los archivos CSV
data_path = '/content/drive/MyDrive/2020-Gasto-COVID-19.csv'
dic_path = '/content/drive/MyDrive/Gasto_COVID_19_Diccionario.csv'

# Leer el conjunto de datos principal
data = pd.read_csv(data_path, encoding='latin1')

# Leer el diccionario de datos
diccionario = pd.read_csv(dic_path, encoding='latin1')

"""Inspeccionamiento de datos y diccionario de datos"""

# Mostrar las primeras filas de los datos
print("Datos principales:")
print(data.head())

print("\nDiccionario de datos:")
print(diccionario.head())